mypro/mainapp/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^detail/(?P<pk>[0-9]+)/$', login_required(views.PostDetailView.as_view()), name='detail'),
    url(r'^comment/post/(?P<pk>[0-9]+)/$', views.comments, name='comments'),
    url(r'^tag/post/(?P<pk>[0-9]+)/$', views.TagPosts.as_view(), name='tag_posts'),
    url(r'^category/post/(?P<pk>[0-9]+)/$', views.CategoryPosts.as_view(), name='category_posts'),
    url(r'^about_me/$', views.about, name='about'),
    url(r'^contact_me/$', login_required(views.contact), name='contact'),
    #url(r'^search/$', views.search, name='search'),
]

mypro/mypro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainapp.urls', namespace='mainapp')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^search/', include('haystack.urls')),
]

mypro/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

mypro/mainapp/models.py
from django.db import models
from django.urls import reverse
# User是一个自带的模型类，里面是用户的字段
# from django.contrib.auth.models import User
from users.models import User
from markdown import Markdown
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=64)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    # 摘要
    excerpt = models.CharField(max_length=256, blank=True)
    # 关系
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User)
    # 文章阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 看不到的属性：comment_set

    class Meta:
        ordering = ['-created_time', '-modified_time']

    def get_absolute_url(self):
        # 使用reverse函数，生成一个url，例如 post / 1
        return reverse('mainapp:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:32]
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=64)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post')

    def __str__(self):
        return self.text[:20]


class Me(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:20]


class Message(models.Model):
    name = models.CharField(max_length=32)
    email = models.EmailField(max_length=64)
    text = models.TextField()

    def __str__(self):
        return self.text[:20]

mypro/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        pass

mypro/mainapp/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name',
            'email',
            'url',
            'text',
        ]

mypro/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

mypro/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post, Tag, Category, Me, Message, Comment
from .forms import CommentForm
from markdown import markdown
from django.db.models import Q

# def index(request):
#     return render(request, 'mainapp/index.html')


class IndexView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = 'mainapp/index.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        num = {"num": 0, }
        context.update(num)
        print(context.get('num'))
        return context


class PostDetailView(DetailView):
    template_name = 'mainapp/single.html'
    model = Post
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super().get_object(queryset=None)
        post.body = markdown(post.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_list = self.object.comment_set.all()
        form = CommentForm()
        context.update({'comment_list': comment_list, 'form': form, })
        return context


def comments(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        print("******************")
        text = request.POST.get('text')
        print(text)
        name = request.user
        email = request.user.email
        url = "http://www.baidu.com"
        result = request.POST
        data = Comment()
        data.name = name
        data.email = email
        data.url = url
        data.text = text
        data.post = post
        # result['name'] = name
        # result['email'] = email
        # result['url'] = url
        # form = CommentForm(result)

        # form.text = text
        # if form.is_valid():
        print("####################")
        # comment = form.save(commit=False)
        # comment.post = post
        # comment.save()
        data.save()
    return redirect(post)


class TagPosts(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(tags=tag)


class CategoryPosts(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super().get_queryset().filter(category=cate)
    # pass


def about(request):
    me = Me.objects.all()
    if me:
        me = me[0].text
    else:
        me = False
    return render(request, 'mainapp/about.html', {'me': me})


def contact(request):
    if request.method == 'POST':
        name = request.user
        email = request.user.email
        message = request.POST.get('message')
        msg = Message()
        msg.name = name
        msg.email = email
        msg.text = message
        msg.save()
        request.session['send_email'] = True
        return redirect("mainapp:contact")
    else:
        flag = request.session.get('send_email')
        request.session['send_email'] = False
        return render(request, 'mainapp/contact.html')


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'mainapp/index.html',
                      {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) |
                                    Q(body__icontains=q))
    return render(request, 'mainapp/index.html',
                  {'error_msg': error_msg,
                  'post_list': post_list})

mypro/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = RegisterForm()
        return render(request, 'users/register.html', context={'form': form})

mypro/templates/mainapp/about.html
{% extends 'mainapp/base.html' %}
{% load blog_tags %}
{% block title %}关于我{% endblock title %}
{% block main %}
{% load staticfiles %}
        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a>关于我</a>
                </div>
            </div>
        </div>
    </header>

    <div class="widewrapper main">
        <div class="container about">
        {% if me %}
            {{ me }}
        {% else %}
            暂无介绍！
        {% endif %}
            <hr>
        </div>
    </div>
    {% endblock main %}
        {% block main1 %}
        {% endblock main1 %}

mypro/templates/mainapp/base.html
{% load staticfiles %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <!--<title>首页</title>-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <style>span.highlighted {  color: red;  }</style>
    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="theme-styles">

    <!--[if lt IE 9]>
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->

</head>
<body>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="{% url 'mainapp:index' %}" id="logo">
                    <img src="{% static 'img/logo.png' %}" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">

                            <li>
                                <a href="{% url 'mainapp:index' %}">首页</a>
                            </li>
                            <li>
                                <a href="{% url 'mainapp:about' %}">关于我</a>
                            </li>
                            <li>
                                <a href="{% url 'mainapp:contact' %}">联系我</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="cl-effect-11"><a href="{% url 'logout' %}">退出</a></li>
                            <li class="cl-effect-11"><a href="{% url 'password_change' %}">修改密码</a></li>
                            {% else %}
                            <li class="cl-effect-11"><a href="{% url 'login' %}">登录</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>

            </div>
        </div>
    <div style="margin-bottom: 50px">
            {% block main %}
            {% endblock %}
    {% block main1 %}
                <aside class="col-md-4 blog-aside">

                    <div class="aside-widget">
                        <header>
                            <h3>热门文章</h3>
                        </header>
                        <div class="body">
                            <ul class="clean-list">
                                {% get_hot_posts as hot_posts %}
                                    {% for post in hot_posts %}
                                        <li><a href="{% url 'mainapp:detail' post.pk %}">{{ post.title }}</a></li>
                                    {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="aside-widget">
                        <header>
                            <h3>最近文章</h3>
                        </header>
                        <div class="body">
                            <ul class="clean-list">
                                {% get_recent_posts as recent_posts %}
                                {% for post in recent_posts %}

                                    <li><a href="{% url 'mainapp:detail' post.pk %}">{{ post.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="aside-widget">
                        <header>
                            <h3>标签</h3>
                        </header>
                        <div class="body clearfix">
                            <ul class="tags">
                                {% get_all_tags as all_tags %}
                                {% for tag in all_tags %}
                                    <li><a href="{% url 'mainapp:tag_posts' tag.pk %}">{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </aside>
    {% endblock %}
</div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/modernizr.js"></script>
</body>
</html>

mypro/templates/mainapp/contact.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>联系我</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">

    <!-- Google Webfonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600|PT+Serif:400,400italic' rel='stylesheet' type='text/css'>

    <!-- Styles -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" id="theme-styles">

    <!--[if lt IE 9]>      
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->
    
</head>
<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="index.html" id="logo">
                    <img src="{% static 'img/logo.png' %}" alt="clean Blog">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                          
                             <li>
                                <a href="{% url 'mainapp:index' %}">首页</a>
                            </li>
                            <li>
                                <a href="{% url 'mainapp:about' %}">关于我</a>
                            </li>
                            <li>
                                <a>联系我</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="cl-effect-11"><a href="{% url 'logout' %}">Logout</a></li>{% else %}
                            <li class="cl-effect-11"><a href="{% url 'login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>        

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb">
                    <a href="#">联系我</a>
                </div>

            </div>
        </div>
    </header>

    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 clean-superblock" id="contact">
                    <h2>联系我</h2>
                    
                    <form action="{% url 'mainapp:contact' %}" method="post" accept-charset="utf-8" class="contact-form">
                        {% csrf_token %}
                          <textarea rows="10" name="message" id="contact-body" placeholder="信息" class="form-control input-lg"></textarea>
                        <div class="buttons clearfix">
                            <button type="submit" class="btn btn-xlarge btn-clean-one">提交</button>
                        </div>                    
                    </form>
                </div>
            </div>        
        </div>
    </div>

   <footer style="margin-bottom: 0px">
        <div class="widewrapper copyright">
              本网站为开源网站，获取源码请访问<a href="https://github.com/limingzhi-95/Django_blog">GitHub</a>或联系博主
        </div>
    </footer>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/js/modernizr.js' %}"></script>

</body>
</html>

mypro/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load blog_tags %}
{% block title %}首页{% endblock title %}
{% block main %}
<div class="widewrapper subheader">
    <div class="container">
        <div class="clean-breadcrumb">
            <a href="#">博客</a>
        </div>

        <div class="clean-searchbox">
            <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                <input class="searchfield" name="q" id="searchbox" type="text" placeholder="Search">
                <button class="searchbutton" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </form>
        </div>
    </div>
</div>


<div class="widewrapper main">

    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-main">
                <div class="row">
                    {% for post in post_list %}
                    {% if forloop.counter < 3 %}
                    <div class="col-md-6 col-sm-6">
                        <article class=" blog-teaser">
                            <header>
                                <h3><a href="{% url 'mainapp:detail' post.pk %}">{{ post.title }}</a></h3>
                                <span class="meta">{{ post.created_time }}</span>
                                <hr>
                            </header>
                            <div class="body">
                                {{ post.excerpt }}
                            </div>
                            <div class="clearfix">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-clean-one">阅读全文</a>
                            </div>
                        </article>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% if post_list.count > 2 %}
                <div class="row">
                    {% for post in post_list %}
                    {% if forloop.counter > 2 %}
                    <div class="col-md-6 col-sm-6">
                        <article class="blog-teaser">
                            <header>
                                <h3><a href="{% url 'mainapp:detail' post.pk %}">{{ post.title }}</a></h3>
                                <span class="meta">{{ post.created_time }}</span>
                                <hr>
                            </header>
                            <div class="body">
                                {{ post.excerpt }}
                            </div>
                            <div class="clearfix">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-clean-one">阅读全文</a>
                            </div>
                        </article>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <div class="paging">
                    <a href="#" class="older">Older Post</a>
                </div>
            </div>
            {% endblock main %}
        </div>
    </div>
</div>


mypro/templates/mainapp/single.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block main %}
    <div class="widewrapper subheader">
        <div class="container">
            <div class="clean-breadcrumb">
                <a href="{% url 'mainapp:index' %}">博客</a>
                <span class="separator">&#x2F;</span>
                <a href="{% url 'mainapp:category_posts' post.category.pk %}">{{ post.category }}</a>
                <span class="separator">&#x2F;</span>
                <a href="#">{{ post.title }}</a>
            </div>


            <div class="clean-searchbox">
                <form action="#" method="get" accept-charset="utf-8">

                    <input class="searchfield" id="searchbox" type="text" placeholder="Search">
                    <button class="searchbutton" type="submit">
                        <i class="fa fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
    </header>

    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
                    <article class="blog-post">
                        <header>

                        </header>
                        <div class="body">
                            <h1>{{ post.title }}</h1>
                            <div class="meta">
                                <i class="fa fa-user"></i> {{ post.author }} <i
                                    class="fa fa-calendar"></i>{{ post.created_time }}<i
                                    class="fa fa-comments"></i><span class="data"><a
                                    href="#comments">阅读量{{ post.views }}</a></span>
                            </div>
                            {{ post.body|safe }}
                        </div>
                    </article>
                    <aside class="social-icons clearfix">
                    </aside>
                    <aside class="comments" id="comments">
                        <hr>

                        <h2><i class="fa fa-comments"></i> {{ comment_list.count }} 条评论</h2>
                        {% for comment in comment_list %}
                            <article class="comment">
                                <header class="clearfix">
                                    {#                                <img src="img/avatar.png" alt="A Smart Guy" class="avatar">#}
                                    <div class="meta">
                                        <h3><a href="#">{{ comment.name }}</a></h3>
                                        <span class="date">
                                        {{ comment.created_time }}
                                    </span>
                                        {#                                    <span class="separator">#}
                                        {#                                        -#}
                                        {#                                    </span>#}
                                        {#                                    此处提供回复评论功能，暂时不添加#}
                                        {#                                    <a href="#create-comment" class="reply-link">Reply</a>                #}
                                    </div>
                                </header>
                                <div class="body">
                                    {{ comment.text }}
                                </div>
                            </article>
                        {% endfor %}
                        {#                            此为回复评论#}
                        {#                        <article class="comment reply">#}
                        {#                            <header class="clearfix">#}
                        {#                                <img src="img/avatar.png" alt="A Smart Guy" class="avatar">#}
                        {#                                <div class="meta">#}
                        {#                                    <h3><a href="#">John Doe</a></h3>#}
                        {#                                    <span class="date">#}
                        {#                                        24 August 2015#}
                        {#                                    </span>#}
                        {#                                    <span class="separator">#}
                        {#                                        -#}
                        {#                                    </span>#}
                        {#                                    #}
                        {#                                    <a href="#create-comment" class="reply-link">Reply</a>                #}
                        {#                                </div>#}
                        {#                            </header>#}
                        {#                             <div class="body">#}
                        {#                               Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere sit perspiciatis debitis, vel ducimus praesentium expedita, assumenda ipsum cum corrupti dolorum modi. Rem ipsam similique sapiente obcaecati tenetur beatae voluptatibus.#}
                        {#                            </div>#}
                        {#                        </article>#}

                    </aside>
                    <aside class="create-comment" id="create-comment">
                        <hr>

                        <h2><i class="fa fa-pencil"></i> 你的评论</h2>

                        <!--<form action="{% url 'mainapp:comments' post.pk %}" method="post" accept-charset="utf-8">-->
                            <!--{% csrf_token %}-->
                            <!--<div class="row">-->
                                <!--<div class="col-md-6">-->
                                    <!--<label for="form.name.id_for_label">名字</label>-->
                                    <!--{{ form.name }}-->
                                    <!--{{ form.name.error }}-->
                                    <!--{#                                    <input type="text" name="name" id="comment-name" placeholder="Your Name" class="form-control input-lg">    #}-->
                                <!--</div>-->
                                <!--<div class="col-md-6">-->
                                    <!--<label for="form.email.id_for_label">邮箱</label>-->
                                    <!--{{ form.email }}-->
                                    <!--{{ form.email.error }}-->
                                    <!--{#                                    <input type="email" name="email" id="comment-email" placeholder="Email" class="form-control input-lg">    #}-->
                                <!--</div>-->
                            <!--</div>-->
                            <!--<div class="col-md-12">-->
                                <!--<label for="form.url.id_for_label">网址</label>-->
                                <!--{{ form.url }}-->
                                <!--{{ form.url.error }}-->
                            <!--</div>-->
                            <!--{#                            <input type="url" name="name" id="comment-url" placeholder="Website" class="form-control input-lg">#}-->

                            <!--{#                            <textarea rows="10" name="message" id="comment-body" placeholder="Your Message" class="form-control input-lg"></textarea>#}-->
                            <!--<div class="col-md-12">-->
                                <!--<label for="form.text.ib_for_label">内容</label>-->
                                <!--{{ form.text }}-->
                                <!--{{ form.text.error }}-->
                            <!--</div>-->
                            <!--<div class="buttons clearfix">-->
                                <!--<button type="submit" class="btn btn-xlarge btn-clean-one">提交</button>-->
                            <!--</div>-->

                        <!--</form>-->
                        <div class="col-md-12">
                         <form action="{% url 'mainapp:comments' post.pk %}" method="post" accept-charset="utf-8" class="contact-form">
                        {% csrf_token %}
                          <textarea rows="10" name="text" id="contact-body" placeholder="评论" class="form-control input-lg"></textarea>
                        <div class="buttons clearfix">
                            <button type="submit" class="btn btn-xlarge btn-clean-one">提交</button>
                        </div>
                    </form>
                        </div>

                    </aside>

                </div>
{% endblock main %}

mypro/templates/users/register.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-
scale=1.0, user-scalable=no">
<title>注册</title>
<link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
<style>
.errorlist {
color: red;
}
</style>
</head>
<body>
<div class="flex-center">
<div class="container">
<div class="flex-center">
<div class="unit-1-2 unit-1-on-mobile">
<h1><a href="{% url 'mainapp:index' %}">Django Auth Example</a></h1>
<h3>注册</h3>
<form class="form" action="{% url 'users:register' %}"
method="post">
{% csrf_token %}
{% for field in form %}
{{ field.label_tag }}
{{ field }}
{{ field.errors }}
{% if field.help_text %}
<p class="help text-small text-
muted">{{ field.help_text|safe }}</p>
{% endif %}
{% endfor %}
<button type="submit" class="btn btn-primary btn-block">注册
</button>
<input type="hidden" name="next" value="{{ next }}"/>
</form>
<div class="flex-center top-gap text-small">
{#<a href="{% url 'login' %}">已有账号登录</a>#}
</div>
</div>
</div>
</div>
</div>
</body>
</html>